In [3]:
import pandas as pd

# Load the dataset
df = pd.read_csv("/Users/akshay/Desktop/dsbda_practical/newdata/adult_dataset.csv")

# --- s. Create data subsets for different Country, Sex, Race ---
us_data = df[df['native-country'] == 'United-States']
female_data = df[df['gender'] == 'Female']
white_race_data = df[df['race'] == 'White']

print("\nSubset: US Data")
print(us_data.head())

# --- t. Merge two subsets (Female + White Race) ---
merged_df = pd.concat([female_data, white_race_data]).drop_duplicates()
print("\nMerged Subset (Female + White Race):")
print(merged_df.head())

# --- u. Sort Data using 'hours-per-week' (used as proxy for 'customer ratings') ---
sorted_df = df.sort_values(by='hours-per-week', ascending=False)
print("\nSorted Data by hours-per-week (proxy for ratings):")
print(sorted_df.head())

# --- v. Transposing Data (first 3 rows) ---
transposed_df = df.head(3).transpose()
print("\nTransposed Data:")
print(transposed_df)

# --- w. Melting Data to Long Format ---
df = df.reset_index()  # Give unique index
melted_df = pd.melt(df, 
                    id_vars=['index','income'], 
                    value_vars=['age', 'hours-per-week', 'capital-gain', 'capital-loss'],
                    var_name='feature', 
                    value_name='value')

print("\nMelted Data (Long Format):")
print(melted_df.head())

# --- x. Casting Data to Wide Format ---
wide_df = melted_df.pivot_table(index='index', 
                                 columns='feature', 
                                 values='value')

# Add back income column for context
wide_df = wide_df.merge(df[['index','income']], on='index')
print("\nCasted Data (Wide Format):")
print(wide_df.head())

Subset: US Data
   age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married
1   38    Private   89814       HS-grad                9  Married-civ-spouse
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse
3   44    Private  160323  Some-college               10  Married-civ-spouse
4   18          ?  103497  Some-college               10       Never-married

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0
1    Farming-fishing      Husband  White    Male             0             0
2    Protective-serv      Husband  White    Male             0             0
3  Machine-op-inspct      Husband  Black    Male          7688             0
4                  ?    Own-child  White  Female             0             0

   hours-per-week native-country income
0              40  United-States  <=50K
1              50  United-States  <=50K
2              40  United-States   >50K
3              40  United-States   >50K
4              30  United-States  <=50K

Merged Subset (Female + White Race):
    age workclass  fnlwgt     education  educational-num      marital-status  \
4    18         ?  103497  Some-college               10       Never-married
8    24   Private  369667  Some-college               10       Never-married
12   26   Private   82091       HS-grad                9       Never-married
17   43   Private  128354       HS-grad                9  Married-civ-spouse
18   37   Private   60548       HS-grad                9             Widowed

           occupation   relationship   race  gender  capital-gain  \
4                   ?      Own-child  White  Female             0
8       Other-service      Unmarried  White  Female             0
12       Adm-clerical  Not-in-family  White  Female             0
17       Adm-clerical           Wife  White  Female             0
18  Machine-op-inspct      Unmarried  White  Female             0

    capital-loss  hours-per-week native-country income
4              0              30  United-States  <=50K
8              0              40  United-States  <=50K
12             0              39  United-States  <=50K
17             0              30  United-States  <=50K
18             0              20  United-States  <=50K

Sorted Data by hours-per-week (proxy for ratings):
       age  workclass  fnlwgt     education  educational-num  \
35422   59    Private  106748       7th-8th                4
2690    37  Local-gov  130805    Assoc-acdm               12
39930   45    Private  390368  Some-college               10
2392    34    Private  230246       HS-grad                9
45468   31    Private  178370       HS-grad                9

           marital-status       occupation   relationship   race  gender  \
35422  Married-civ-spouse    Other-service           Wife  White  Female
2690   Married-civ-spouse  Protective-serv        Husband  White    Male
39930  Married-civ-spouse            Sales        Husband  Black    Male
2392        Never-married     Craft-repair  Not-in-family  White    Male
45468            Divorced    Other-service      Unmarried  White  Female

       capital-gain  capital-loss  hours-per-week native-country income
35422             0             0              99  United-States  <=50K
2690              0             0              99  United-States   >50K
39930         15024             0              99  United-States   >50K
2392           2202             0              99  United-States  <=50K
45468             0             0              99  United-States   >50K

Transposed Data:
                                 0                   1                   2
age                             25                  38                  28
workclass                  Private             Private           Local-gov
fnlwgt                      226802               89814              336951
education                     11th             HS-grad          Assoc-acdm
educational-num                  7                   9                  12
marital-status       Never-married  Married-civ-spouse  Married-civ-spouse
occupation       Machine-op-inspct     Farming-fishing     Protective-serv
relationship             Own-child             Husband             Husband
race                         Black               White               White
gender                        Male                Male                Male
capital-gain                     0                   0                   0
capital-loss                     0                   0                   0
hours-per-week                  40                  50                  40
native-country       United-States       United-States       United-States
income                       <=50K               <=50K                >50K

Melted Data (Long Format):
   index income feature  value
0      0  <=50K     age     25
1      1  <=50K     age     38
2      2   >50K     age     28
3      3   >50K     age     44
4      4  <=50K     age     18

Casted Data (Wide Format):
   index   age  capital-gain  capital-loss  hours-per-week income
0      0  25.0           0.0           0.0            40.0  <=50K
1      1  38.0           0.0           0.0            50.0  <=50K
2      2  28.0           0.0           0.0            40.0   >50K
3      3  44.0        7688.0           0.0            40.0   >50K
4      4  18.0           0.0           0.0            30.0  <=50K